require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/ClassLength:
  Max: 240

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ModuleLength:
  Max: 200

RSpec/DescribeClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedDescription:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - 'spec/easy_talk/examples/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Lint/EmptyBlock:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
  
RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockNesting:
  Max: 10
